# Generated by Django 3.2.8 on 2021-10-24 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('body', models.CharField(default='', max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('answer', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
