# Generated by Django 3.2.8 on 2021-10-24 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='createAt',
        ),
        migrations.AddField(
            model_name='question',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
