# Generated by Django 3.2.8 on 2021-10-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_auto_20211024_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
