# Generated by Django 3.2.8 on 2021-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_auto_20211024_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='writer',
            field=models.TextField(default='', max_length=50),
        ),
    ]
