# Generated by Django 3.2.8 on 2021-11-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueOverflowDB', '0003_auto_20211029_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questionAsked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.JSONField(default=''),
        ),
    ]
