# Generated by Django 3.2.8 on 2021-11-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueOverflowDB', '0005_alter_answer_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='questionAsked',
            new_name='Asked',
        ),
    ]
