# Generated by Django 3.2.8 on 2021-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueOverflowDB', '0006_rename_questionasked_tag_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.JSONField(),
        ),
    ]
