# Generated by Django 3.2.8 on 2021-11-04 10:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueOverflowDB', '0007_auto_20211104_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
