# Generated by Django 3.2.8 on 2021-11-09 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueOverflowDB', '0009_question_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
